const product_card = [
  {
    id: 1,
    product_name: "Men Shirt",
    description: "Lorem ipsum dolor sit ame",
    currency: "$",
    price: 29,
    thumb: "./images/1.png",
  },
  {
    id: 2,
    product_name: "Sneaker Nike",
    description: "Lorem ipsum dolor sit ame",
    currency: "$",
    price: 39,
    thumb: "./images/2.png",
  },
  {
    id: 3,
    product_name: "Puma Sneaker",
    description: "Lorem ipsum dolor sit ame",
    currency: "$",
    price: 30,
    thumb: "./images/3.png",
  },
  {
    id: 4,
    product_name: "Alonzi Dress",
    description: "Lorem ipsum dolor sit ame",
    currency: "$",
    price: 19,
    thumb: "./images/4.png",
  },
  {
    id: 5,
    product_name: "Men Watch",
    description: "Lorem ipsum dolor sit ame",
    currency: "$",
    price: 16,
    thumb: "./images/5.png",
  },
  {
    id: 6,
    product_name: "Men Cap",
    description: "Lorem ipsum dolor sit ame",
    currency: "$",
    price: 10,
    thumb: "./images/6.png",
  },
  {
    id: 7,
    product_name: "Ladies Jeans",
    description: "Lorem ipsum dolor sit ame",
    currency: "$",
    price: 40,
    thumb: "./images/7.png",
  },
  {
    id: 8,
    product_name: "Long Sleeves",
    description: "Lorem ipsum dolor sit ame",
    currency: "$",
    price: 35,
    thumb: "./images/8.png",
  },
];

export default product_card;
